language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.8"
  - "5.12"
  - "6.10"
  - "7.10"

sudo: false

matrix:
  fast_finish: true

install:
  - npm install

script:
  - npm test

notifications:
  on_success: never
  on_failure: always